name: MLOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests
      run: PYTHONPATH=. pytest tests/test_app.py
      
    - name: Build Docker Image (M3)
      run: docker build -t mlops-service:latest .
      
    - name: Local CD & Smoke Test (M4)
      run: |
        docker-compose up -d
        sleep 5
        python smoke_test.py
        docker-compose down